language: go
go:
  - 1.1
  - tip
before_install:
  - cd
  - wget https://leveldb.googlecode.com/files/leveldb-1.10.0.tar.gz
  - tar xzf leveldb-1.10.0.tar.gz
  - cd leveldb-1.10.0
  - make
  - export LEVELDB=`pwd`
  - CGO_CFLAGS="-I`pwd`/include" CGO_LDFLAGS="-L`pwd`" go get github.com/jmhodges/levigo
  - cd $TRAVIS_BUILD_DIR
install:
  - go get -d -v ./... && go build -v ./...
  - go get launchpad.net/gocheck
script:
  - LD_LIBRARY_PATH=$LEVELDB go test -v ./...
