language: go
before_install:
  - wget https://leveldb.googlecode.com/files/leveldb-1.10.0.tar.gz
  - tar xzf leveldb-1.10.0.tar.gz
  - cd leveldb-1.10.0
  - make
  - CGO_CFLAGS="-I`pwd`/include" CGO_LDFLAGS="-L`pwd`" go get github.com/jmhodges/levigo
  - cd ..
  - go get launchpad.net/gocheck
